### ISSUE TITLE
file format mismacth

### ISSUE THREAD

**Issue by Xujianyugit** [fanglab/mbin#10]
* mbin version:1.1.1
* Python version:2.7
* Operating System:Linux Ubuntu

### Description

"""How are you.I am honor to send emails to you ask some questions.
After reading your article 'Metagenomic binning and association of plasmids with bacterial host genomes using DNA methylation',I want to conduct the same analyse of metagenomic data in Nanopore sequence.I read your document about "mBin" in GitHub.But your analyse is carried by pacbio dataset.You use the wga_aligned_reads.cmp.h5 file to obtain a set of control IPD values,but this file is unique in pacbio sequence.While Nanopore sequence only have fast5 files.So what should I do to get the same files in Nanopore sequence?
"""

### What I Did
###Can you give me some ideas about this problem？
###Thank you very much and I am looking forward to your replay.

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.

###buildcontrols -i --procs=4 --control_pkl_name=control_means.pkl ###wga_aligned_reads.cmp.h5
```

**Comment by jbeaulaurier** [comment]
Hello,
Thanks so much for you interest in the package. Unfortunately, mbin is only compatible with PacBio sequencing data. The nanopore sequencing data form for methylation detection is dramatically different, so making mbin nanopore compatible would be a very non-trivial task and is not currently planned.
Best,
John

**Comment by Xujianyugit** [comment]
Ok,I see.
Thank you very much for your apply!
