### ISSUE TITLE
About the input file format

### ISSUE THREAD

**Issue by ZhangZhenmiao** [fanglab/mbin#11]
Hi,

My pacbio data format is bam and bam.pbi, but the input file format of mbin is cmp.h5. Is mbin compatible with bam? If not, is there a way to transform a bam file to cmp.h5?

Thanks.

**Comment by jbeaulaurier** [comment]
Unfortunately, the newer BAM file formats from PacBio are not currently supported and there are no current plans to add BAM compatibility. I would suggest you contact PacBio support to see whether they have any tools available for converting BAM to cmp.h5 format.
